// Code generated by rice embed-go; DO NOT EDIT.
package main

import (
	"time"

	"github.com/GeertJohan/go.rice/embedded"
)

func init() {

	// define files
	file2 := &embedded.EmbeddedFile{
		Filename:    "demo.css",
		FileModTime: time.Unix(1576074588, 0),

		Content: string(".container {\n    width: 400px;\n    height: 100px;\n    background-color: #009ACD;\n    margin: auto;\n}\n\n.text {\n    position: relative;\n    top: 50%;\n    transform: translateY(-50%);\n    text-align: center;\n    color: #FFFFFF;\n}"),
	}
	file3 := &embedded.EmbeddedFile{
		Filename:    "demo.html",
		FileModTime: time.Unix(1576074654, 0),

		Content: string("<html>\n<head>\n    <title>BANK Questionnaire</title>\n    <link rel=\"stylesheet\" href=\"demo.css\" />\n</head>\n<body>\n<div class=\"container\">\n    <p id=\"text\" class=\"text\"></p>\n</div>\n<script src=\"demo.js\"></script>\n</body>\n</html>"),
	}
	file4 := &embedded.EmbeddedFile{
		Filename:    "demo.js",
		FileModTime: time.Unix(1576074614, 0),

		Content: string("document.getElementById(\"text\").innerHTML = \"Bank Questionnaire<br /><p>Demo Page</p>\";"),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1576074654, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file2, // "demo.css"
			file3, // "demo.html"
			file4, // "demo.js"

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`UI`, &embedded.EmbeddedBox{
		Name: `UI`,
		Time: time.Unix(1576074654, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir1,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"demo.css":  file2,
			"demo.html": file3,
			"demo.js":   file4,
		},
	})
}
