SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
CREATE TABLE [dbo].[QUESTION_BANK] (
	[id] [INT] IDENTITY(1, 1) NOT NULL,
	[serialNo] [INT] NOT NULL,
	[text] [VARCHAR] (512) NOT NULL,
	[isDeleted] [BIT] DEFAULT(0) NOT NULL,
	[createdOn] [DATETIME] DEFAULT(GETDATE()) NULL,
	[createdBy] [VARCHAR] (64) NOT NULL,
	[updatedOn] [DATETIME] DEFAULT(GETDATE()) NULL,
	[updatedBy] [VARCHAR] (64) NOT NULL,
	CONSTRAINT [QUESTION_BANK_PK_ID] PRIMARY KEY CLUSTERED ([id] ASC)
);
--DROP TABLE [dbo].[QUESTION_BANK];
