SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
CREATE TABLE [dbo].[CUSTOMER_QUESTIONS] (
	[questionId] [INT] NOT NULL,
	[customerId]	[VARCHAR] (64) NOT NULL ,
	[answer] [VARCHAR] (512) NOT NULL,
	[isDeleted] [BIT] DEFAULT(0) NOT NULL,
	[createdOn] [DATETIME] DEFAULT(GETDATE()) NULL,
	[createdBy] [VARCHAR] (64) NOT NULL,
	[updatedOn] [DATETIME] DEFAULT(GETDATE()) NULL,
	[updatedBy] [VARCHAR] (64) NOT NULL,
	CONSTRAINT [CUSTOMER_QUESTIONS_PK_ID] PRIMARY KEY CLUSTERED ([questionId],[customerId] ASC)
);