SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE [dbo].[SP_CUSTOMER_QUESTIONS_VALIDATE] (
	@customerId VARCHAR (64), @questionId int
)
AS
BEGIN
	SET ANSI_NULLS ON;
	SET ANSI_PADDING ON;
	SET QUOTED_IDENTIFIER ON;
	SET NOCOUNT ON;

	SELECT [answer]
	FROM [dbo].[CUSTOMER_QUESTIONS] WITH (NOLOCK)
	WHERE [isDeleted] = 0 AND [customerId] = @customerId AND [questionId] = @questionId;

END;
