SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE [dbo].[SP_CUSTOMER_QUESTIONS_GET_QUESTION_ID] (
	@customerId VARCHAR (64)
)
AS
BEGIN
	SET ANSI_NULLS ON;
	SET ANSI_PADDING ON;
	SET QUOTED_IDENTIFIER ON;
	SET NOCOUNT ON;

	SELECT [questionId]
	FROM [dbo].[CUSTOMER_QUESTIONS] WITH (NOLOCK)
	WHERE [isDeleted] = 0 AND [customerId] = @customerId
	ORDER BY [createdOn] ASC;
END;